const mongoose=require('mongoose');const Doctor=require('../models/Doctor');const Token=require('../models/Token');const Counter=require('../models/TokenCounter');
const date=()=>new Date().toISOString().slice(0,10);
exports.createToken=async({hospitalId,doctorId,patientName,phoneNumber,reason,source='walk_in'})=>{if(!mongoose.isValidObjectId(hospitalId)||!mongoose.isValidObjectId(doctorId))throw Error('Invalid hospital or doctor');const d=await Doctor.findOne({_id:doctorId,hospitalId});if(!d)throw Error('Doctor not found');if(d.status==='offline')throw Error('Doctor is offline');const businessDate=date();const c=await Counter.findOneAndUpdate({hospitalId,businessDate},{$inc:{sequence:1}},{new:true,upsert:true});return Token.create({hospitalId,doctorId,tokenNumber:c.sequence,patientName,phoneNumber,reason,source,businessDate});};
exports.getQueue=async({doctorId,businessDate=date()})=>Token.find({doctorId,businessDate,status:{$in:['waiting','called','in_consultation']}}).sort({tokenNumber:1}).lean();
exports.callNext=async({doctorId,businessDate=date()})=>{const d=await Doctor.findById(doctorId);if(!d)throw Error('Doctor not found');if(d.status!=='available')throw Error('Doctor is not available');if(d.currentTokenId)throw Error('Doctor already has an active patient');const t=await Token.findOneAndUpdate({doctorId,businessDate,status:'waiting'},{$set:{status:'called',calledAt:new Date()}},{sort:{tokenNumber:1},new:true});if(!t)throw Error('No patients waiting');d.currentTokenId=t._id;await d.save();return t;};
exports.start=async doctorId=>{const d=await Doctor.findById(doctorId);if(!d?.currentTokenId)throw Error('No patient called');const t=await Token.findOneAndUpdate({_id:d.currentTokenId,status:'called'},{$set:{status:'in_consultation',startedAt:new Date()}},{new:true});if(!t)throw Error('Unable to start consultation');return t;};
exports.complete=async doctorId=>{const d=await Doctor.findById(doctorId);if(!d?.currentTokenId)throw Error('No active patient');const t=await Token.findOneAndUpdate({_id:d.currentTokenId,status:'in_consultation'},{$set:{status:'completed',completedAt:new Date()}},{new:true});if(!t)throw Error('Unable to complete consultation');d.currentTokenId=null;await d.save();return t;};
exports.skip=async doctorId=>{const d=await Doctor.findById(doctorId);if(!d?.currentTokenId)throw Error('No active patient');const t=await Token.findOneAndUpdate({_id:d.currentTokenId,status:{$in:['called','in_consultation']}},{$set:{status:'skipped',skippedAt:new Date()}},{new:true});d.currentTokenId=null;await d.save();return t;};
exports.setBreak=async(doctorId,onBreak)=>{const d=await Doctor.findById(doctorId);if(!d)throw Error('Doctor not found');if(onBreak&&d.currentTokenId)throw Error('Finish current patient first');d.status=onBreak?'on_break':'available';return d.save();};
